version: 1.0.{build}

image: Ubuntu

environment:
  MOZBUILD_PATH: /home/appveyor/.mozbuild

cache:
  - /home/appveyor/.mozbuild

# Only build on tags
skip_non_tags: true

install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential make msitools wget unzip python3 python3-dev python3-pip git p7zip-full golang-go aria2

build_script:
  - make setup-minimal
  - make mozbootstrap
  - mkdir -p dist

test_script:
  - python3 ./multibuild.py --target windows macos linux --arch x86_64

artifacts:
  - path: dist/*
    name: CamoufoxBuilds

deploy:
  provider: GitHub
  auth_token:
    secure: $(GITHUB_TOKEN)
  artifact: CamoufoxBuilds
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
