version: 1.0.{build}

image: Ubuntu

environment:
  MOZBUILD_PATH: /home/appveyor/.mozbuild

cache:
  - /home/appveyor/.mozbuild

# Only build on tags
skip_non_tags: true

init:
  - export PATH=/home/appveyor/venv3.11/bin:$PATH

install:
  - sudo apt-get install -y msitools aria2
  - make setup-minimal
  - make mozbootstrap
  - mkdir -p dist

build_script:
  - python3 ./multibuild.py --target windows macos linux --arch x86_64

artifacts:
  - path: dist/*
    name: CamoufoxBuilds

deploy:
  provider: GitHub
  auth_token:
    secure: $(GITHUB_TOKEN)
  artifact: CamoufoxBuilds
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
