name: Build and Release Wheel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        working-directory: ./pythonlib
        run: |
          pip install poetry

      - name: Build wheel
        working-directory: ./pythonlib
        run: |
          poetry install
          poetry build

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: pythonlib/dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}