name: Upload Local Built Wheel to GitHub Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Version from wheel filename
        id: get_version
        run: |
          FILE=$(ls pythonlib/dist/*.whl | head -n 1)
          echo "WHEEL_FILE=$FILE" >> $GITHUB_ENV
          VERSION=$(basename $FILE | cut -d- -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          files: ${{ env.WHEEL_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}